-- =============================================================================
-- KV Table Creation SQL
-- Generated by: ./create_kv_table.sh
-- Generation time: 2025-12-15 14:43:52
-- =============================================================================

-- Parameters:
--   Range partition count: 4
--   Key subpartition count: 48
--   Start timestamp: 2024-01-01 00:00:00 (1704038400000 ms)
--   Partition duration: 31536000000 ms

-- Start timestamp (formatted): 2024-01-01 00:00:00
-- Partition duration: 365 days

-- =============================================================================

CREATE TABLE kv_table (
    pmid CHAR(36) NOT NULL,
    ts TIMESTAMP(6) NOT NULL,
    value DOUBLE,
    PRIMARY KEY (pmid, ts)
)
PARTITION BY RANGE COLUMNS (ts)
SUBPARTITION BY KEY(pmid) SUBPARTITIONS 48
(
    PARTITION p0 VALUES LESS THAN ('2024-12-31 00:00:00'),
    PARTITION p1 VALUES LESS THAN ('2025-12-31 00:00:00'),
    PARTITION p2 VALUES LESS THAN ('2026-12-31 00:00:00'),
    PARTITION p3 VALUES LESS THAN (MAXVALUE)
);

